theme: jekyll-theme-minimal
Title: Ali Kianian
Description1: Tehran-Iran 
Description2: +989354024978 - ali.kianian1990@gmail.com
Description3: [Download Resume](alikianian.pdf).
logo: kianian.jpg
show_downloads: false
